spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/horse_cafe
    username: sa
    password:
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        use_sql_comments: true
  jwt:
    secret-key: SECRET_KEY

logging:
  level:
    org.hibernate.SQL: debug